config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for(:users)

  get("up" => "rails/health#show", as: :rails_health_check)
  get("/trades/chart_data", to: "trades#chart_data")

  root("home#index")
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/trade.rb
# frozen_string_literal: true

class Trade < ApplicationRecord
  STOCK_SYMBOL_AAPL = "AAPL"
  STOCK_SYMBOL_FAKEPACA = "FAKEPACA" # stock symbol used for sandbox
  STOCK_SYMBOLS = (%w[INST ORCL TSLA] + [STOCK_SYMBOL_AAPL, STOCK_SYMBOL_FAKEPACA]).sort.freeze
  CHART_TIME_FORMAT = "%H:%M:%S"

  # Alpaca's free market data offering includes live data only from the IEX exchange
  # https://docs.alpaca.markets/docs/historical-stock-data-1#data-sources
  EXCHANGE_NAME_IEX = "IEX"
  EXCHANGE_NAMES = [EXCHANGE_NAME_IEX].freeze

  validates(:stock_symbol, presence: true, inclusion: { in: STOCK_SYMBOLS })
  validates(:exchange_name, presence: true, inclusion: { in: EXCHANGE_NAMES })
  validates(:exchange_trade_id, presence: true)
  validates(:price, presence: true, numericality: { greater_than: 0 })
  validates(:quantity, presence: true, numericality: { only_integer: true, greater_than: 0 })
  validates(:timestamp, presence: true)

  after_create_commit(:broadcast_trade_to_channel)

  def formatted_timestamp
    timestamp.strftime(CHART_TIME_FORMAT)
  end

  private

  def broadcast_trade_to_channel
    broadcast_replace_to(
      "trade_channel_#{stock_symbol}",
      target: "stimulus_target_#{stock_symbol}"
    )
  end
end

app/models/trade_channel.rb
# frozen_string_literal: true

class TradeChannel < ApplicationRecord
  belongs_to(:user)

  validates(:stock_symbol, presence: true, inclusion: { in: Trade::STOCK_SYMBOLS })
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many(:trade_channels, dependent: :destroy)

  validates(:name, presence: true)

  devise(:database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable)
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser(versions: :modern)

  # Override the Devise redirection after sign-out
  def after_sign_out_path_for(_resource_or_scope)
    new_user_session_path
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action(:authenticate_user!)
  def index
    @trade_channels = current_user.trade_channels
  end
end

app/controllers/trades_controller.rb
# frozen_string_literal: true

class TradesController < ApplicationController
  before_action(:authenticate_user!)

  def chart_data
    trades = latest_trades.reverse.map do |trade|
      [trade.formatted_timestamp, trade.price.to_f]
    end.transpose
    labels, values = trades
    render(
      json: {
        labels: labels || [],
        values: values || []
      }
    )
  end

  private

  def latest_trades
    trades = Trade.order(timestamp: :desc)
    trades = trades.where(stock_symbol: params[:stock_symbol]) if params[:stock_symbol].present?
    trades.limit(50)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/home/_trade_channel.html.erb
<div
  data-controller="chart"
  data-chart-url-value="<%= trades_chart_data_path(stock_symbol: trade_channel.stock_symbol) %>"
  data-chart-symbol-value="<%= trade_channel.stock_symbol %>"
  class="chart card w-2/4">
  <h3 class="text-center" data-chart-target="symbolAndPrice"></h3>
  <canvas data-chart-target="chart"></canvas>
</div>

<div id="stimulus_target_<%= trade_channel.stock_symbol %>"></div>

<%= turbo_stream_from "trade_channel_#{trade_channel.stock_symbol}" %>

app/views/home/index.html.erb
<div class="flex flex-row w-full justify-center gap-8">
  <%= render partial: "trade_channel", collection: @trade_channels %>
</div>

app/views/layouts/_header.html.erb
<header class="bg-white p-1 shadow-md">
  <div class="flex justify-between items-center w-full">
    <h1 class="logo text-3xl ml-6">Market Watcher</h1>
    <%= button_to destroy_user_session_path, method: :delete, class: "btn-secondary px-2 py-1", title: "Logout" do %>
      <span class="sr-only">Logout</span>
      <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5 transform rotate-180" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
        <path d="M17 9h-6V5l-5 5 5 5v-4h6V9z" />
        <path d="M4 4h6a1 1 0 00-1-1H4a2 2 0 00-2 2v10a2 2 0 002 2h6a1 1 0 001-1H4V4z" />
      </svg>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Market Watcher" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="h-screen bg-orange-100/50">
     <% if user_signed_in? %>
      <div class="flex flex-col h-screen">
        <%= render "layouts/header" %>

        <main class="flex flex-row p-6">
          <%= yield %>
        </main>
      </div>
    <% else %>
      <div class="h-screen flex items-center justify-center">
        <main class="p-6 bg-white shadow-md rounded">
          <%= yield %>
        </main>
      </div>
    <% end %>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% if flash[:alert] %>
  <div class="flash bg-red-100 border-red-400 text-red-700">
    <%= flash[:alert] %>
  </div>
<% end %>
<% if flash[:notice] %>
  <div class="flash bg-green-100 border-green-400 text-green-700">
    <%= flash[:notice] %>
  </div>
<% end %>

app/views/trades/_trade.html.erb
<div
  id="stimulus_target_<%= trade.stock_symbol %>"
  data-controller="trade-updater"
  data-trade-updater-chart-outlet=".chart"
  data-trade-updater-symbol-value="<%= trade.stock_symbol %>"
  data-trade-updater-price-value="<%= trade.price %>"
  data-trade-updater-time-value="<%= trade.formatted_timestamp %>"
></div>